# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, ci-test ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: actions/checkout
      uses: actions/checkout@v2
    - name: actions/setup-node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Install dependencies
      run: |
        npm install -g pnpm
        pnpm install
    - name: Run tests
      run : pnpm run test
